name: CI
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d

      - name: Run tests
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run nosetests -v
